Create guide for EnTT
FrederoxDev/Bedrock-Modding-Guide pull request #1
Opened 2024-05-13 22:11 UTC by ZeroMemes

2024-05-13 22:14 UTC, FrederoxDev commented
I'll write up any feedback tomorrow morning 👍 

First pass, looks good though! Thanks

2024-05-14 06:44 UTC, FrederoxDev requested changes

2024-05-14 06:44 UTC, FrederoxDev commented on docs/advanced-topics/entt.md
> +Mojang has configured EnTT in multiple ways to suit the needs of Minecraft: Bedrock Edition. In order to have binary
Maybe word the last bit as something in like "In order for mods to have binary...", this just makes it more clear what subject you're referring to after you were talking about the game

2024-05-14 06:45 UTC, FrederoxDev commented
Other than that one piece of feedback I gave, this is really well written in a formal manner 👍 

I appreciate you contributing to this wiki too, thanks!

2024-05-15 23:35 UTC, ZeroMemes commented
Went a bit beyond the originally intended scope and added guides on how to setup Clang/how to address EnTT type hash issues with Clang, but it should be ready for a merge if everything looks good.

2024-05-16 07:42 UTC, FrederoxDev approved these changes

2024-05-16 07:42 UTC, FrederoxDev commented
Looks good to me 👍

2024-05-16 07:43 UTC, merged